# Generated by Django 5.2.13 on 2026-05-05 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('result', models.CharField(choices=[('accepted', 'Accepte'), ('refused', 'Refuse')], max_length=20, verbose_name='resultat')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='date de paiement')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='commande')),
            ],
            options={
                'ordering': ('-processed_at',),
            },
        ),
    ]
