# Generated by Django 5.2.13 on 2026-06-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-processed_at',), 'verbose_name': 'paiement', 'verbose_name_plural': 'paiements'},
        ),
    ]
