# Generated by Django 5.2.13 on 2026-05-05 23:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('artist', models.CharField(max_length=200, verbose_name='artiste ou groupe')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('starts_at', models.DateTimeField(verbose_name='date et heure')),
                ('venue', models.CharField(max_length=200, verbose_name='lieu')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouvert a la vente'), ('sold_out', 'Complet'), ('cancelled', 'Annule'), ('finished', 'Termine')], default='draft', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise a jour')),
            ],
            options={
                'ordering': ('starts_at', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='prix')),
                ('stock_initial', models.PositiveIntegerField(verbose_name='stock initial')),
                ('stock_remaining', models.PositiveIntegerField(verbose_name='stock restant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise a jour')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_categories', to='concerts.concert', verbose_name='concert')),
            ],
            options={
                'ordering': ('concert', 'name'),
                'constraints': [models.UniqueConstraint(fields=('concert', 'name'), name='unique_seat_category_name_per_concert'), models.CheckConstraint(condition=models.Q(('stock_initial__gte', 0)), name='seat_category_stock_initial_non_negative'), models.CheckConstraint(condition=models.Q(('stock_remaining__gte', 0)), name='seat_category_stock_remaining_non_negative')],
            },
        ),
    ]
