# Generated by Django 5.2.13 on 2026-06-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouvert a la vente'), ('closed', 'Vente cloturee'), ('sold_out', 'Complet'), ('cancelled', 'Annule'), ('finished', 'Termine')], default='draft', max_length=20, verbose_name='statut'),
        ),
    ]
