# Generated by Django 5.2.13 on 2026-06-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_add_closed_concert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('open', 'Ouvert à la vente'), ('closed', 'Vente clôturée'), ('sold_out', 'Complet'), ('cancelled', 'Annulé'), ('finished', 'Terminé')], default='draft', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
    ]
