# Generated by Django 5.2.13 on 2026-06-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_alter_concert_created_at_alter_concert_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ('starts_at', 'title'), 'verbose_name': 'concert', 'verbose_name_plural': 'concerts'},
        ),
        migrations.AlterModelOptions(
            name='seatcategory',
            options={'ordering': ('concert', 'name'), 'verbose_name': 'catégorie de place', 'verbose_name_plural': 'catégories de places'},
        ),
    ]
