# Generated by Django 5.2.13 on 2026-05-05 23:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('checked_out', 'Valide'), ('abandoned', 'Abandonne')], default='active', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise a jour')),
                ('concert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carts', to='concerts.concert', verbose_name='concert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='quantite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise a jour')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cart.cart', verbose_name='panier')),
                ('seat_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_lines', to='concerts.seatcategory', verbose_name='categorie de place')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='unique_active_cart_per_user'),
        ),
        migrations.AddConstraint(
            model_name='cartline',
            constraint=models.UniqueConstraint(fields=('cart', 'seat_category'), name='unique_cart_line_per_seat_category'),
        ),
        migrations.AddConstraint(
            model_name='cartline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 6)), name='cart_line_quantity_between_1_and_6'),
        ),
    ]
