# Generated by Django 5.2.13 on 2026-06-15 05:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('concerts', '0003_alter_concert_created_at_alter_concert_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('checked_out', 'Validé'), ('abandoned', 'Abandonné')], default='active', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='cartline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='cartline',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='cartline',
            name='seat_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_lines', to='concerts.seatcategory', verbose_name='catégorie de place'),
        ),
        migrations.AlterField(
            model_name='cartline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
    ]
