# Generated by Django 5.2.13 on 2026-06-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_created_at_alter_cart_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-created_at',), 'verbose_name': 'panier', 'verbose_name_plural': 'paniers'},
        ),
        migrations.AlterModelOptions(
            name='cartline',
            options={'ordering': ('id',), 'verbose_name': 'ligne de panier', 'verbose_name_plural': 'lignes de panier'},
        ),
    ]
