# Generated by Django 5.2.13 on 2026-05-05 23:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payee'), ('refused', 'Refusee'), ('cancelled', 'Annulee')], default='pending', max_length=20, verbose_name='statut')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='montant total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de mise a jour')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='concerts.concert', verbose_name='concert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_snapshot', models.CharField(max_length=120, verbose_name='categorie achetee')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='prix unitaire')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='quantite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de creation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.order', verbose_name='commande')),
                ('seat_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='concerts.seatcategory', verbose_name='categorie de place')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 6)), name='order_line_quantity_between_1_and_6')],
            },
        ),
    ]
