# Generated by Django 5.2.13 on 2026-06-15 05:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_alter_concert_created_at_alter_concert_status_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payée'), ('refused', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='category_name_snapshot',
            field=models.CharField(max_length=120, verbose_name='catégorie achetée'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de création'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='quantité'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='seat_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='concerts.seatcategory', verbose_name='catégorie de place'),
        ),
    ]
