# Generated by Django 5.2.13 on 2026-06-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_created_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'commande', 'verbose_name_plural': 'commandes'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'ordering': ('id',), 'verbose_name': 'ligne de commande', 'verbose_name_plural': 'lignes de commande'},
        ),
    ]
